apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment4
  labels:
    app: assignment4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment4
  template:
    metadata:
      name: assignment4
      labels:
        app: assignment4
    spec:
      containers:
        - name: assignment4
          image: assignment4
          imagePullPolicy: Never
          ports:
            - containerPort: 8383
---
apiVersion: v1
kind: Service
metadata:
  name: assignment4
  labels:
    app:  assignment4
spec:
  selector:
    app: assignment4
  ports:
    - name: http
      port: 8383
      targetPort: 8383
  #type: NodePort type of service
